- platform: generic
  name: Current location
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.iphonealex.attributes.latitude }},{{ states.device_tracker.iphonealex.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:Alex%7C{{ states.device_tracker.iphonealex.attributes.latitude }},{{ states.device_tracker.iphonealex.attributes.longitude }}
  limit_refetch_to_url_change: true