homeassistant:
  name: !secret HOME_NAME
  latitude: !secret HOME_LATITUDE
  longitude: !secret HOME_LONGITUDE
  elevation: !secret HOME_ELAVATION
  unit_system: metric
  time_zone: !secret HOME_TIME_ZONE

  # Customization file
  customize: !include_dir_merge_named customizations

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Enables configuration Hassio
hassio:

recorder:
  purge_interval: 1
  purge_keep_days: 2
  db_url: !secret RECORDER_DB_URL

http:
  api_password: !secret HTTP_PASSWORD
  ssl_certificate: !secret SSL_CERTIFICATE
  ssl_key: !secret SSL_KEY

# Checks for available updates
updater:
  reporting: true
  include_used_components: true

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

nest:
  client_id: !secret NEST_CLIENT_ID
  client_secret: !secret NEST_CLIENT_SECRET
  binary_sensors:
    monitored_conditions:
  sensors:
    monitored_conditions:
      - 'humidity'
      - 'operation_mode'
      - 'temperature'
      - 'target'
      - 'hvac_state'
  
rfxtrx:
  device: /dev/ttyUSB1

zwave:
  usb_path: /dev/ttyACM0
  device_config:
    sensor.greenwave_powernode_6_kantoor_power:
      polling_intensity: 1

# Platforms
light: !include platforms/lights.yaml
media_player: !include platforms/media_players.yaml
remote: !include platforms/remotes.yaml
device_tracker: !include platforms/device_trackers.yaml
sensor: !include_dir_merge_list platforms/sensors
binary_sensor: !include_dir_merge_list platforms/binary_sensors
camera: !include_dir_merge_list platforms/cameras

tradfri:
  host: !secret TRADFRI_HOST
  allow_tradfri_groups: false

apple_tv:
  - host: !secret APPLETV_HOST
    login_id: !secret APPLETV_LOGIN_ID
    name: "Apple TV"

group: !include_dir_merge_named groups
zone: !include zones.yaml
automation: !include automations.yaml
script: !include scripts.yaml

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml
