- platform: template
  sensors:
    philio_technology_corporation_pst02a_4_in_1_multisensor_access:
      value_template: '{{ is_state("sensor.philio_technology_corporation_pst02a_4_in_1_multisensor_access_control", "22") }}'
      device_class: opening
      entity_id: sensor.philio_technology_corporation_pst02a_4_in_1_multisensor_access_control

    philio_technology_corporation_pst02a_4_in_1_multisensor_motion:
      value_template: '{{ is_state("sensor.philio_technology_corporation_pst02a_4_in_1_multisensor_burglar", "8") }}'
      device_class: motion
      entity_id: sensor.philio_technology_corporation_pst02a_4_in_1_multisensor_burglar

    philio_technology_corporation_pst02a_4_in_1_multisensor_tamper:
      value_template: '{{ is_state("sensor.philio_technology_corporation_pst02a_4_in_1_multisensor_burglar", "3") }}'
      device_class: safety
      entity_id: sensor.philio_technology_corporation_pst02a_4_in_1_multisensor_burglar