- platform: template
  sensors:
    pst02a_kantoor_access:
      value_template: '{{ is_state("sensor.pst02a_kantoor_access_control", "22") }}'
      device_class: opening
      entity_id: sensor.pst02a_kantoor_access_control

    pst02a_kantoor_motion:
      value_template: '{{ is_state("sensor.pst02a_kantoor_burglar", "8") }}'
      device_class: motion
      entity_id: sensor.pst02a_kantoor_burglar

    pst02a_kantoor_tamper:
      value_template: '{{ is_state("sensor.pst02a_kantoor_burglar", "3") }}'
      device_class: safety
      entity_id: sensor.pst02a_kantoor_burglar