- platform: rfxtrx
  automatic_add: True
  devices:
    0a520d05460100c7400149:
       name: Badkamer
       data_type:
        - Humidity
        - Temperature
    0a520d06f30100c43d0159:
      name: Babykamer
      data_type:
       - Humidity
       - Temperature