- platform: synologydsm
  host: !secret SYNOLOGY_HOST
  username: !secret SYNOLOGY_USERNAME
  password: !secret SYNOLOGY_PASSWORD
  monitored_conditions:
    # Displays unspecified load in percentage.
    # - cpu_other_load
    # Displays user load in percentage.
    # - cpu_user_load
    # Displays system load in percentage
    # - cpu_system_load
    # Displays combined load in percentage.
    - cpu_total_load
    # Displays maximum load in past minute.
    # - cpu_1min_load
    # Displays maximum load in past 5 minutes.
    # - cpu_5min_load
    # Displays maximum load in past 15 minutes.
    # - cpu_15min_load
    # Displays percentage of memory used.
    - memory_real_usage
    # Displays total size of memory in MB.
    - memory_size
    # Displays total size of cache in MB.
    # - memory_cached
    # Displays total size of available swap in MB.
    # - memory_available_swap
    # Displays total size of memory used (based on real memory) in MB.
    # - memory_available_real
    # Displays total size of actual memory in MB.
    # - memory_total_swap
    # Displays total size of real memory in MB.
    # - memory_total_real
    # Displays total up speed of network interfaces (combines all interfaces).
    - network_up
    # Displays total down speed of network interfaces (combines all interfaces).
    - network_down
    # Displays the name of the harddisk (creates a new entry for each disk).
    # - disk_name
    # Displays the path of the harddisk (creates a new entry for each disk).
    # - disk_device
    # Displays the S.M.A.R.T status of the harddisk (creates a new entry for each disk).
    - disk_smart_status
    # Displays the status of the harddisk (creates a new entry for each disk).
    - disk_status
    # Displays true / false to indicate if the harddisk exceeded the maximum bad sector threshold (creates a new entry for each disk).
    - disk_exceed_bad_sector_thr
    # Displays true / false to indicate if the harddisk dropped below the remain life threshold (creates a new entry for each disk).
    - disk_below_remain_life_thr
    # Displays the temperature of the harddisk (creates a new entry for each disk, uses the unit_system to display in C or F).
    - disk_temp
    # Displays the status of the volume (creates a new entry for each volume).
    - volume_status
    # Displays the volume type (RAID, etc) (creates a new entry for each volume).
    # - volume_device_type
    # Displays the total size of the volume in GB’s (creates a new entry for each volume).
    - volume_size_total
    # Displays the used space on this volume in GB’s (creates a new entry for each volume).
    - volume_size_used
    # Displays the percentage used for this volume in GB’s (creates a new entry for each volume).
    - volume_percentage_used
    # Displays the average temperature of all disks in the volume (creates a new entry for each volume).
    # - volume_disk_temp_avg
    # Displays the maximum temperature of all disks in the volume (creates a new entry for each volume).
    # - volume_disk_temp_max
